### ISSUE TITLE
执行后遇到个问题

### ISSUE THREAD

**Issue by oliverzhong** [YxMingY/BaiduCloudPanLinkCatcher#1]
Input your keyword: linux
Your keyword: linux
initialization...

Warning: file_get_contents(): Unable to find the wrapper "https" - did you forget to enable it when you configured PHP? in /home/jie/Code/test/BaiduCloudPanLinkCatcher/Scheduler.php on line 41

Warning: file_get_contents(https://m.baidu.com/from=844b/pu=sz%401321_1001/s?word=linux+%E7%99%BE%E5%BA%A6%E4%BA%91): failed to open stream: No such file or directory in /home/jie/Code/test/BaiduCloudPanLinkCatcher/Scheduler.php on line 41
start!
Array
(
)

**Comment by YxMingY** [comment]
Well, check whether you installed and enabled the php extension 'php_openssl'.
For Windows, add 'extension=php_openssl.dll' at any line in your php.ini
For Linux, install the openssl extension according to https://www.cnblogs.com/iaknehc/p/7628022.html.
emm你好像是中国人诶我为什么要用英语

**Comment by YxMingY** [comment]
Anything else?
